### PR TITLE
WIP: Swapping mysql for percona

### PR DESCRIPTION
**Pull request by Leopere**
Completely untested but stored for now in case we want to start reviewing this.

### CODE REVIEW

**Review by EnigmaCurry — APPROVED** [review]

**Comment by EnigmaCurry** [comment]
#71 is using this same percona image and is currently ingesting data, I will let it go for awhile and see how it performs.

**Comment by Leopere** [comment]
@EnigmaCurry is this still a WIP?  From my reading, Percona should be a drop-in replacement for mariadb and mysql.

**Comment by EnigmaCurry** [comment]
Percona itself (this image) is working fine (identically to MySQL afaict) so I don't see a problem with merging this.

However, I did end up removing percona from #71 because the helm chart for percona is not as well fleshed out as the MySQL one.

**Comment by Leopere** [comment]
@EnigmaCurry how about instead of redoing the [prod-example](https://github.com/lbryio/lbry-docker/blob/3d2362c9e861e3e2f85ab603d099f52ec4c66e0a/chainquery/compose/docker-compose.yml-prod-example) docker-compose file we add a new example and call this one merge-able.  Perhaps mention it in the README.md as another possible option.

**Comment by Leopere** [comment]
I'm going to consider this not necessary and abandon it for now based off of feedback from lbry staff.

**Pull request closed without merging**
