### PR TITLE
Refactor lbrynet compiler dockerfiles into one

### PR DESCRIPTION
**Pull request by EnigmaCurry**
[Dockerfiles can have FROM lines that have ARGs](https://github.com/docker/cli/blob/master/docs/reference/builder.md#understand-how-arg-and-from-interact)

This means we can refactor the lbrynet compiler Dockerfiles into one.

### CODE REVIEW

**Comment by EnigmaCurry** [comment]
I don't see anyway to specify a build-arg on the docker-hub build page... so this may be a non-starter.

**Comment by Leopere** [comment]
We will avoid this for now and consider it for maybe a different feature add in the future as it will require a fair bit of work to get GitLab working and setup for our CI/CD process.

**Comment by Leopere** [comment]
Explanation of the hook builds.
https://github.com/docker/hub-feedback/issues/508#issuecomment-222520720
https://docs.docker.com/docker-hub/builds/advanced/#override-build-test-or-push-commands

**Comment by EnigmaCurry** [comment]
So I got rid of the hook builds, as it's not necessary for this use-case. The way the ARG is setup, it has a default of ubuntu:18.04, and it [successfully builds for x86](https://cloud.docker.com/repository/registry-1.docker.io/enigmacurry/lbry-docker/builds/ddef3ddb-b7bd-4e0b-9fce-898a968fa49a) on docker-hub without any need to specify the build-arg. Since they won't build the arm images anyway, I think this is sufficient for now.

**Review by Leopere — APPROVED** [review]
I'm happy with this PR

**Pull request merged**
