### PR TITLE
Major Refactor WIP

### PR DESCRIPTION
**Pull request by Leopere**
This refactor PR is a work in progress, @EnigmaCurry, and I are cleaning up this repository now that we've committed ourselves to just doing all of the container orchestration from within this repository rather than getting in the way of others within the LBRY Inc organization.

### CODE REVIEW

**Comment by Leopere** [comment]
Depends on updates to this issue referenced https://github.com/lbryio/lbry-docker/issues/36#issuecomment-486881385

**Comment by tiger5226** [comment]
this needs to be squashed something fierce. 

image

**Comment by Leopere** [comment]
The refactor needs documentation updates and a twice over to ensure that there are no dangling references and a final squash & rebase.

**Comment by Leopere** [comment]
I've read through all of the documentation to verify things are copacetic, and I feel that things are relatively concise and functional no dangling URL or tag references I've set up the following repositories to build the docker files within this repository.
```
https://hub.docker.com/r/lbry/lbrynet
https://hub.docker.com/r/lbry/chainquery
https://hub.docker.com/r/lbry/lbrycrd
```
There will need to be a huge overhaul of documentation but that's out of scope for this refactor.

**Comment by Leopere** [comment]
Closes #35 and closes #22

**Comment by Leopere** [comment]
Closes #49

**Comment by Leopere** [comment]
Closes #36

**Pull request merged**
